[package]
name = "corolla"
version = "0.1.0"
edition = "2021"
description = "\"your liteweight backend\""
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.20", features = ["macros"] }
clap = { version = "4.4.6", features = ["derive"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
sqlx = { version = "0.7.2", features = ["sqlite", "runtime-tokio", "macros"]}
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
