[package]
name = "corolla"
version = "0.2.2"
edition = "2021"
description = "\"your liteweight backend\""
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.7.4", features = ["macros"] }
clap = { version = "4.4.18", features = ["derive"] }
log = "0.4.21"
pretty_env_logger = "0.5.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
sqlx = { version = "0.7.2", features = ["sqlite", "runtime-tokio", "macros"]}
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
pretty_assertions = "1.4.0"
reqwest = { version = "0.11.24", features = ["blocking", "json"] }
