name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - name: Build
      run: cargo build --verbose
    - name: Run cargo test
      run: timeout 300 cargo test --verbose
    - name: Run bun test against test server
      run: bun test
