name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run cargo test
      run: cargo test --verbose
    - name: Run background corolla server
      run: |
       cargo run -- -s examples/example_spec.json -d tmp/$(date +%s).sqlite3 -r /test &
       sleep 5
       bun test
